version: '3.8'
services:
  tor:
    container_name: tor
    image: lncm/tor:0.4.7.8@sha256:aab30ebb496aa25934d6096951d8b200347c3c3ce5db3493695229efa2601f7b
    user: toruser
    restart: on-failure
    volumes:
    - ${PWD}/tor/torrc-core:/etc/tor/torrc
    - ${PWD}/tor/data:/var/lib/tor/
    ports:
    - 127.0.0.1:$TOR_PROXY_PORT:$TOR_PROXY_PORT
    networks:
      default:
        ipv4_address: $TOR_PROXY_IP
  app-tor:
    container_name: app-tor
    image: lncm/tor:0.4.7.8@sha256:aab30ebb496aa25934d6096951d8b200347c3c3ce5db3493695229efa2601f7b
    user: toruser
    restart: on-failure
    volumes:
    - ${PWD}/tor/torrc-apps:/etc/tor/torrc
    - ${PWD}/tor/data:/var/lib/tor/
    networks:
      default:
        ipv4_address: $APPS_TOR_IP
  app-2-tor:
    container_name: app-2-tor
    image: lncm/tor:0.4.7.8@sha256:aab30ebb496aa25934d6096951d8b200347c3c3ce5db3493695229efa2601f7b
    user: toruser
    restart: on-failure
    volumes:
    - ${PWD}/tor/torrc-apps-2:/etc/tor/torrc
    - ${PWD}/tor/data:/var/lib/tor/
    networks:
      default:
        ipv4_address: $APPS_2_TOR_IP
  app-3-tor:
    container_name: app-3-tor
    image: lncm/tor:0.4.7.8@sha256:aab30ebb496aa25934d6096951d8b200347c3c3ce5db3493695229efa2601f7b
    user: toruser
    restart: on-failure
    volumes:
    - ${PWD}/tor/torrc-apps-3:/etc/tor/torrc
    - ${PWD}/tor/data:/var/lib/tor/
    networks:
      default:
        ipv4_address: $APPS_3_TOR_IP
  nginx:
    container_name: nginx
    image: nginx:1.21.6@sha256:2834dc507516af02784808c5f48b7cbe38b8ed5d0f4837f16e78d00deb7e7767
    depends_on:
    - dashboard
    - manager
    volumes:
    - ${PWD}/nginx:/etc/nginx
    restart: on-failure
    stop_grace_period: 30s
    ports:
    - ${NGINX_PORT}:80
    - 433:433
    - ${NGINX_SSL_PORT}:443
    networks:
      default:
        ipv4_address: $NGINX_IP
  bitcoin:
    container_name: bitcoin
    image: nolim1t/bitcoinknots:v22.0.knots20211108@sha256:a475da2b2ecda55fcc65ea23e1a36c58b2c10549f1c3d3bb3c31c7dda1127354
    depends_on:
    - tor
    volumes:
    - ${PWD}/bitcoin:/data/.bitcoin
    restart: on-failure
    stop_grace_period: 1m
    ports:
    - $BITCOIN_P2P_PORT:$BITCOIN_P2P_PORT
    networks:
      default:
        ipv4_address: $BITCOIN_IP
  lightning:
    container_name: lightning
    image: lightninglabs/lnd:v0.15.0-beta@sha256:d227a9db0727ff56020c8d6604c8c369757123d238ab6ce679579c2dd0d0d259
    user: 1000:1000
    depends_on:
    - tor
    - bitcoin
    volumes:
    - ${PWD}/lnd:/data/.lnd
    - ${PWD}/walletpassword:/walletpassword
    environment:
      HOME: /data
    restart: on-failure
    stop_grace_period: 5m30s
    ports:
    - 9735:9735
    - $LND_REST_PORT:$LND_REST_PORT
    - $LND_GRPC_PORT:$LND_GRPC_PORT
    networks:
      default:
        ipv4_address: $LND_IP
  dashboard:
    container_name: dashboard
    image: ghcr.io/runcitadel/dashboard:fix-small-issues-and-translations@sha256:82059a11e50d77eec8edb20a8c0e1f821988ea176b928944738df1a93304c26e
    restart: on-failure
    stop_grace_period: 1m30s
    networks:
      default:
        ipv4_address: $DASHBOARD_IP
  manager:
    container_name: manager
    image: ghcr.io/runcitadel/manager:v0.0.16@sha256:9de3acad76e957811ff7f81cdba8b9a280a79762d24e1bcd16a4517e5643dfca
    depends_on:
    - tor
    - redis
    command:
    - ./start.sh
    restart: on-failure
    init: true
    stop_grace_period: 5m30s
    volumes:
    - ${PWD}/info.json:/info.json
    - ${PWD}/db:/db
    - ${PWD}/events:/events
    - ${PWD}/apps:/apps
    - ${PWD}/lnd:/lnd:ro
    - ${PWD}/statuses:/statuses
    - ${PWD}/tor/data:/var/lib/tor/
    - jwt-public-key:/jwt-public-key
    - jwt-private-key:/jwt-private-key
    environment:
      PORT: '3006'
      USER_PASSWORD_FILE: /db/user.json
      JWT_PUBLIC_KEY_FILE: /jwt-public-key/jwt.pem
      JWT_PRIVATE_KEY_FILE: /jwt-private-key/jwt.key
      JWT_EXPIRATION: '3600'
      DEVICE_HOSTS: ${DEVICE_HOSTS:-"http://citadel.local"}
      DEVICE_HOSTNAME: ${DEVICE_HOSTNAME:-""}
      MIDDLEWARE_API_URL: http://$MIDDLEWARE_IP
      SEED_FILE: /db/citadel-seed/seed
      BITCOIN_P2P_PORT: $BITCOIN_P2P_PORT
      BITCOIN_RPC_PORT: $BITCOIN_RPC_PORT
      BITCOIN_RPC_USER: $BITCOIN_RPC_USER
      BITCOIN_RPC_PASSWORD: $BITCOIN_RPC_PASS
      LND_CERT_FILE: /lnd/tls.cert
      LND_ADMIN_MACAROON_FILE: /lnd/data/chain/bitcoin/${BITCOIN_NETWORK}/admin.macaroon
      GITHUB_REPO: runcitadel/core
      GITHUB_BRANCH: ${UPDATE_CHANNEL:-"stable"}
      VERSION_FILE: /info.json
      UPDATE_LOCK_FILE: /statuses/update-in-progress
      BACKUP_STATUS_FILE: /statuses/backup-status.json
      DEBUG_STATUS_FILE: /statuses/debug-status.json
      TOR_PROXY_IP: ${TOR_PROXY_IP}
      TOR_PROXY_PORT: ${TOR_PROXY_PORT}
      TOR_HIDDEN_SERVICE_DIR: /var/lib/tor
      IS_CITADEL_OS: ${IS_CITADEL_OS:-"true"}
      REDIS_PASSWORD: freedom
      REDIS_IP: $REDIS_IP
      REDIS_PORT: 6379
      UNSAFE_REMOVE_CORS_CHECK: true
    networks:
      default:
        ipv4_address: $MANAGER_IP
  middleware:
    container_name: middleware
    image: ghcr.io/runcitadel/middleware:v0.0.11@sha256:e472da8cbfa67d9a9dbf321334fe65cdf20a0f9b6d6bab33fdf07210f54e7002
    depends_on:
    - manager
    - bitcoin
    - lightning
    - redis
    command: sh -c "./wait-for-manager.sh $MANAGER_IP && ./start.sh"
    restart: on-failure
    volumes:
    - ${PWD}/lnd:/lnd
    - jwt-public-key:/jwt-public-key
    environment:
      PORT: '3005'
      BITCOIN_HOST: $BITCOIN_IP
      RPC_PORT: $BITCOIN_RPC_PORT
      RPC_USER: $BITCOIN_RPC_USER
      RPC_PASSWORD: $BITCOIN_RPC_PASS
      LND_NETWORK: $BITCOIN_NETWORK
      LND_HOST: ${LND_IP}
      JWT_PUBLIC_KEY_FILE: /jwt-public-key/jwt.pem
      DEVICE_HOSTS: ${DEVICE_HOSTS:-"http://citadel.local"}
      UNSAFE_REMOVE_CORS_CHECK: true
    networks:
      default:
        ipv4_address: $MIDDLEWARE_IP
  neutrino-switcher:
    container_name: neutrino-switcher
    image: lncm/neutrino-switcher:1.0.5@sha256:3ddf58c5599ba22db8414f2694bfeeba086455d4a19b4955b26c3ae5e967d42a
    depends_on:
    - bitcoin
    - lightning
    restart: on-failure
    volumes:
    - ${PWD}/lnd:/lnd
    - ${PWD}/statuses:/statuses
    - /var/run/docker.sock:/var/run/docker.sock
    environment:
      JSONRPCURL: http://${BITCOIN_IP}:${BITCOIN_RPC_PORT}
      RPCUSER: $BITCOIN_RPC_USER
      RPCPASS: $BITCOIN_RPC_PASS
      LND_CONTAINER_NAME: lightning
      SLEEPTIME: 3600
    networks:
      default:
        ipv4_address: $NEUTRINO_SWITCHER_IP
  electrum:
    container_name: electrum
    image: ghcr.io/runcitadel/electrs:v0.9.6@sha256:cf08513b8aa6f081e42ea92c5903d520db2caedbc20aaccf70f844663bbc8646
    working_dir: /data
    volumes:
    - ${PWD}/bitcoin:/bitcoin:ro
    - ${PWD}/electrs:/data
    restart: on-failure
    stop_grace_period: 5m
    ports:
    - $ELECTRUM_PORT:$ELECTRUM_PORT
    networks:
      default:
        ipv4_address: $ELECTRUM_IP
  redis:
    container_name: redis
    user: 1000:1000
    image: redis:7.0.0-bullseye@sha256:ad0705f2e2344c4b642449e658ef4669753d6eb70228d46267685045bf932303
    working_dir: /data
    volumes:
    - ${PWD}/redis:/data
    command: redis-server --requirepass freedom
    restart: on-failure
    stop_grace_period: 1m
    init: true
    networks:
      default:
        ipv4_address: $REDIS_IP

networks:
  default:
    name: citadel_main_network
    ipam:
      driver: default
      config:
      - subnet: $NETWORK_IP/24
volumes:
  jwt-public-key: null
  jwt-private-key: null
