#!/usr/bin/env bash

# SPDX-FileCopyrightText: 2021-2022 Citadel and contributors
#
# SPDX-License-Identifier: GPL-3.0-or-later

CITADEL_ROOT="$(readlink -f $(dirname "${BASH_SOURCE[0]}")/../..)"

signal="${1}"
command=${signal%%"-"*}
app=${signal#*"-"}

"${CITADEL_ROOT}/scripts/app" "${command}" "${app}"
