#!/usr/bin/env bash

# SPDX-FileCopyrightText: 2021 Umbrel. https://getumbrel.com
#
# SPDX-License-Identifier: PolyForm-Noncommercial-1.0.0

UMBREL_ROOT="$(readlink -f $(dirname "${BASH_SOURCE[0]}")/../..)"

signal="${1}"
command=${signal%%"-"*}
app=${signal#*"-"}

"${UMBREL_ROOT}/app/app-manager.py" "${command}" "${app}"
