#!/usr/bin/env bash

# SPDX-FileCopyrightText: 2021 Aaron Dewes <aaron.dewes@web.de>
#
# SPDX-License-Identifier: GPL-3.0-or-later

CITADEL_ROOT="$(readlink -f $(dirname "${BASH_SOURCE[0]}")/../..)"

"${CITADEL_ROOT}/scripts/citadel-os/change-password"
