#!/usr/bin/env bash

# SPDX-FileCopyrightText: 2021-2022 Citadel and contributors
#
# SPDX-License-Identifier: GPL-3.0-or-later

CITADEL_ROOT="$(readlink -f $(dirname "${BASH_SOURCE[0]}")/../..)"

OUTPUT_FILE="${CITADEL_ROOT}/statuses/available-updates.json"

echo "false" > "${OUTPUT_FILE}"
"${CITADEL_ROOT}/scripts/app" list-updates  > "${OUTPUT_FILE}"
