#!/usr/bin/env bash

# SPDX-FileCopyrightText: 2021 Umbrel. https://getumbrel.com
#
# SPDX-License-Identifier: PolyForm-Noncommercial-1.0.0

set -euo pipefail

RELEASE=$1
UMBREL_ROOT=$2
first_run=$3

LIMIT=3500000

# Warn on low memory devices
memory="$(awk '/MemTotal/{printf "%d\n", $2}' /proc/meminfo)"
if ((memory<LIMIT)); then
    echo "WARNING: Citadel has been designed for devices with 4GB of RAM or more. You may run into issues on this system."
fi
