# SPDX-FileCopyrightText: Gonzalo Aune 
#
# SPDX-License-Identifier: AGPL-3.0-only

# yaml-language-server: $schema=../../app-standard-v1.json

version: 1

metadata:
  category: Social
  name: Sphinx Relay
  version: 2.2.1
  tagline: Chat and pay over the Lightning Network
  description: 'Sphinx Relay turns your Lightning node into a personal communication
    server. Messages are end-to-end encrypted and transmitted over the Bitcoin Lightning
    Network. Download Sphinx on your phone from https://sphinx.chat and pair it with
    Sphinx Relay on Citadel.


    Communication between Sphinx Relay nodes takes place entirely on the Lightning
    Network, so it is decentralized, untraceable, and encrypted. Messages are encrypted
    using client public keys on the Sphinx app.


    You can join tribes at https://tribes.sphinx.chat. If you join a podcast tribe,
    you can listen to the podcast in Sphinx and stream donations to the host.'
  developer: Stakwork
  website: https://sphinx.chat
  dependencies:
  - lnd
  repo: https://github.com/stakwork/sphinx-relay
  support: https://t.me/joinchat/Fb4OcRo4LrRD6NXfsNdeeQ
  gallery:
  - 1.jpg
  - 2.jpg
  - 3.jpg
  path: /connect
containers:
- name: sphinx-relay
  image: sphinxlightning/sphinx-relay:v2.2.1@sha256:9cee7ae739283eb824790b3bd1ba1890e8633598eb2df2cfc4bd01f08e54c5a5
  init: true
  environment:
    PUBLIC_URL: $APP_HIDDEN_SERVICE:$APP_SPHINX_RELAY_PORT
    LND_IP: $LND_IP
    CONNECT_UI: 'true'
    LND_PORT: $LND_GRPC_PORT
    TLS_LOCATION: /lnd/tls.cert
    MACAROON_LOCATION: /lnd/data/chain/bitcoin/${BITCOIN_NETWORK}/admin.macaroon
    LND_LOG_LOCATION: /lnd/logs/bitcoin/${BITCOIN_NETWORK}/lnd.log
  data:
  - data:/relay/.lnd/
  permissions:
  - lnd
