version: 1

metadata:
  category: Automation
  name: Home Assistant
  version: 2021.9.5
  tagline: Home automation that puts local control & privacy first
  description: >-
    Open source home automation that puts local control and privacy first,
    powered by a worldwide community of tinkerers and DIY enthusiasts. Home Assistant
    integrates with over a thousand different devices and services. Once you have
    integrated all your devices at home, you can unleash Home Assistant’s advanced
    automation engine to make your home work for you. Examples:
    
    
    - Turn on the light when the sun sets or when coming home
    
    - Alert you when you leave your garage door open
    
    All your smart home data stays local. Home Assistant communicates
    with your devices locally, and will fallback to pulling in data from the cloud
    if there is no other option. No data is stored in the cloud, and everything
    is processed locally.
  developer: Home Assistant
  website: https://home-assistant.io
  dependencies: []
  repo: https://github.com/home-assistant/core
  support: https://community.home-assistant.io
  gallery:
  - 1.jpg
  - 2.jpg
  - 3.jpg

containers:
- name: server
  image: homeassistant/home-assistant:2021.9.5@sha256:66d80bef139d3039dc933f45f5d98b72829af39801e07f810d94648215e971fd
  port: 8123
  data:
  - data:/config
