# SPDX-FileCopyrightText: 2020 Umbrel. https://getumbrel.com
# SPDX-FileCopyrightText: 2021 Citadel and contributors.
#
# SPDX-License-Identifier: AGPL-3.0-or-later

# Please note: This file can't be changed, it will be overwritten.
# A few modifications will be kept, including alias, color, channel size limitations and more if you contact us.

log_filters = "INFO"
network = "bitcoin"
db_dir = "/data/db"
daemon_dir = "/bitcoin"
daemon_rpc_addr = "<bitcoin-ip>:<bitcoin-rpc-port>"
daemon_p2p_addr = "<bitcoin-ip>:<bitcoin-p2p-port>"
electrum_rpc_addr = "0.0.0.0:<electrum-port>"
server_banner = "Citadel v<citadel-version>"
