#!/usr/bin/env bash

# SPDX-FileCopyrightText: 2020-2021 Umbrel. https://getumbrel.com
#
# SPDX-License-Identifier: PolyForm-Noncommercial-1.0.0

CITADEL_ROOT="$(readlink -f $(dirname "${BASH_SOURCE[0]}")/..)"

resource="${1}"
interval="${2}"

log () {
  echo "$(date "+%Y-%m-%d %H:%M:%S") ${@}"
}

log "Status monitor for \"${resource}\" running every ${interval} seconds!"

status_script="${CITADEL_ROOT}/scripts/status/${resource}"
json_path="${CITADEL_ROOT}/statuses/${resource}-status.json"
while true; do
  result=$("${status_script}")
  echo "$result" > "${json_path}"
  sleep "${interval}"
done
