metadata:
  category: Explorers
  name: Mempool
  version: 2.2.1
  tagline: A mempool visualizer, explorer and fee estimator
  description: 'Mempool is the official self-hosted version of the fully featured
    explorer, visualizer, fee estimator, and API service running on mempool.space,
    an open source project developed and operated for the benefit of the Bitcoin community,
    with a focus on the emerging transaction fee market to help our transition into
    a multi-layer ecosystem.


    Features:


    - Live dashboard visualizing the mempool and blockchain

    - Live transaction tracking

    - Search any transaction, block or address

    - Fee estimations

    - Mempool historical data

    - TV View for larger displays as a TV in a cafe or bar

    - View transaction scripts and op_return messages

    - Audio notifications on transaction confirmed and address balance change

    - Multiple languages support

    - JSON APIs'
  developer: mempool.space
  website: https://mempool.space/about
  dependencies:
  - electrum
  - bitcoind
  repo: https://github.com/mempool/mempool
  support: https://t.me/mempoolspace
  port: 3006
  gallery:
  - 1.jpg
  - 2.jpg
  - 3.jpg
  path: ''
  defaultPassword: ''
containers:
- image: mempool/frontend:v2.2.1@sha256:6c87505b89cce1bb3dd99ff2d59cfac5ff2b78136a0f17fe5c37c3f832b9aff6
  user: 1000:1000
  init: true
  command: ./wait-for mariadb:3306 --timeout=720 -- nginx -g 'daemon off;'
  ports:
  - ${APP_MEMPOOL_PORT}:${APP_MEMPOOL_PORT}
  environment:
    FRONTEND_HTTP_PORT: $APP_MEMPOOL_PORT
    BACKEND_MAINNET_HTTP_HOST: $APP_MEMPOOL_API_IP
  name: web
  ip: $APP_MEMPOOL_IP
- image: mempool/backend:v2.2.1@sha256:175f33ab2e96319c2730c020f28207cef9d1f4cb330eab4f40fa4721d01fa272
  user: 1000:1000
  init: true
  command: ./wait-for-it.sh mariadb:3306 --timeout=720 --strict -- ./start.sh
  environment:
    RPC_HOST: $BITCOIN_IP
    RPC_PORT: $BITCOIN_RPC_PORT
    RPC_USER: $BITCOIN_RPC_USER
    RPC_PASS: $BITCOIN_RPC_PASS
    ELECTRUM_HOST: $ELECTRUM_IP
    ELECTRUM_PORT: $ELECTRUM_PORT
    ELECTRUM_TLS: 'false'
    MYSQL_HOST: $APP_MEMPOOL_DB_IP
    MYSQL_PORT: '3306'
    MYSQL_DATABASE: mempool
    MYSQL_USER: mempool
    MYSQL_PASS: mempool
    BACKEND_MAINNET_HTTP_PORT: '8999'
    CACHE_DIR: /backend/cache
    MEMPOOL_CLEAR_PROTECTION_MINUTES: '20'
  name: api
  data:
  - data:/backend/cache
  permissions:
  - electrum
  - bitcoind
  ip: $APP_MEMPOOL_API_IP
- image: mariadb:10.5.8@sha256:8040983db146f729749081c6b216a19d52e0973134e2e34c0b4fd87f48bc15b0
  user: 1000:1000
  environment:
    MYSQL_DATABASE: mempool
    MYSQL_USER: mempool
    MYSQL_PASSWORD: mempool
    MYSQL_ROOT_PASSWORD: moneyprintergobrrr
  name: mariadb
  data:
  - mysql/db-scripts:/docker-entrypoint-initdb.d
  - mysql/data:/var/lib/mysql
  ip: $APP_MEMPOOL_DB_IP
