#!/usr/bin/env bash

# SPDX-FileCopyrightText: 2021-2022 Citadel and contributors
#
# SPDX-License-Identifier: GPL-3.0-or-later

CITADEL_ROOT="$(readlink -f $(dirname "${BASH_SOURCE[0]}")/../..)"

cat <<EOF > "$CITADEL_ROOT"/statuses/app-update-status.json
{"state": "installing", "progress": 20, "description": "Downloading updates", "updateTo": "$RELEASE"}
EOF
"${CITADEL_ROOT}/scripts/app" update
wait

cat <<EOF > "$CITADEL_ROOT"/statuses/app-update-status.json
{"state": "installing", "progress": 60, "description": "Starting apps", "updateTo": "$RELEASE"}
EOF
"${CITADEL_ROOT}/scripts/app" start installed
cat <<EOF > "$CITADEL_ROOT"/statuses/app-update-status.json
{"state": "success", "progress": 100, "description": "Update successful", "updateTo": "$RELEASE"}
EOF
