#!/usr/bin/env bash

# SPDX-FileCopyrightText: 2021 Umbrel. https://getumbrel.com
#
# SPDX-License-Identifier: PolyForm-Noncommercial-1.0.0

STATUS_FILE_PATH="/citadel-status"

service_id="${1}"
status="${2}"
error_code="${3}"

source /etc/default/citadel 2> /dev/null
if [[ -z "${CITADEL_OS:-}" ]]; then
  echo "Skipping status update when not on Citadel OS"
  exit
fi

if [[ "${service_id}" == "" ]]; then
  echo "Error: Missing ID"
  exit 1
fi

if [[ "${status}" == "" ]]; then
  echo "Error: Missing Status"
  exit 1
fi

entry="${service_id}:${status}"

if [[ "${error_code}" != "" ]]; then
  entry="${entry}:${error_code}"
fi

echo "${entry}" >> "${STATUS_FILE_PATH}"
