metadata:
  category: Development
  name: Gitea
  version: 1.15.2
  tagline: A painless self-hosted Git service
  description: 'Gitea is a painless self-hosted Git service. It is similar to GitHub,
    Bitbucket, and GitLab. It is a community managed lightweight code hosting solution
    written in Go. Gitea''s minimal requirements allow it to run seamlessly on inexpensive
    hardware like a Raspberry Pi. Features:


    - Fully self-hosted and private

    - Issue tracker

    - Account/Organization/Repository management

    - Tor support

    - Repository Git hooks/deploy keys

    - Repository issues, pull requests and wiki

    - Add/Remove repository collaborators

    - Gravatar and custom source

    - Admin panel'
  developer: Gitea
  website: https://gitea.io/en-us/
  dependencies: []
  repo: https://github.com/go-gitea/gitea
  support: https://discourse.gitea.io
  port: 8085
  gallery:
  - 1.jpg
  - 2.jpg
  - 3.jpg
  path: ''
  defaultPassword: ''
  torOnly: false
containers:
- image: gitea/gitea:1.15.2-rootless@sha256:6caabcf0e1a21a2d885f44c8f19693ce44ec3d443e2116f86a2937db453566a8
  user: 1000:1000
  ports:
  - ${APP_GITEA_PORT}:${APP_GITEA_PORT}
  - ${APP_GITEA_SSH_PORT}:${APP_GITEA_SSH_PORT}
  environment:
    GITEA__security__INSTALL_LOCK: 'true'
    GITEA__server__DOMAIN: ${APP_DOMAIN}
    GITEA__server__HTTP_PORT: ${APP_GITEA_PORT}
    GITEA__server__SSH_DOMAIN: ${APP_DOMAIN}
    GITEA__server__SSH_PORT: ${APP_GITEA_SSH_PORT}
    GITEA__server__SSH_LISTEN_PORT: ${APP_GITEA_SSH_PORT}
    GITEA__server__START_SSH_SERVER: 'true'
    GITEA__database__DB_TYPE: mysql
    GITEA__database__HOST: ${APP_GITEA_DB_IP}:3306
    GITEA__database__NAME: gitea
    GITEA__database__USER: gitea
    GITEA__database__PASSWD: moneyprintergobrrr
  name: server
  data:
  - data/gitea/config:/etc/gitea
  - data/gitea/data:/var/lib/gitea
  ip: $APP_GITEA_IP
- image: mariadb:10.6.4@sha256:4bbee12b1adf299211f844ebbe89563675c46965470dcfa40f5278d63c56d030
  user: 1000:1000
  environment:
    MYSQL_ROOT_PASSWORD: gitea
    MYSQL_USER: gitea
    MYSQL_PASSWORD: moneyprintergobrrr
    MYSQL_DATABASE: gitea
  name: db
  data:
  - data/db:/var/lib/mysql
  ip: $APP_GITEA_DB_IP
