metadata:
  category: Networking
  name: Pi-hole
  version: 5.3.1
  tagline: Block ads on your entire network
  description: "Instead of browser plugins or other software on each computer, install\
    \ Pi-hole\xAE on your Umbrel and your entire network is protected. Network-level\
    \ blocking allows you to block ads in non-traditional places such as mobile apps\
    \ and smart TVs, regardless of hardware or OS. Since advertisements are blocked\
    \ before they are downloaded, network performance is improved and will feel faster.\
    \ \n\nIn addition to blocking advertisements, Pi-hole\xAE has an informative Web\
    \ interface that shows stats on all the domains being queried on your network.\
    \ Pi-hole\xAE works fine with an existing DHCP server, but you can use Pi-hole\xAE\
    \u2019s to keep your network management in one place.\n\n Pi-hole\xAE and the\
    \ Pi-hole\xAE logo are registered trademarks of Pi-hole. Umbrel is not sponsored,\
    \ endorsed by, or associated with Pi-hole\xAE."
  developer: "Pi-hole\xAE"
  website: https://pi-hole.net
  dependencies: []
  repo: https://github.com/pi-hole/pi-hole
  support: https://discourse.pi-hole.net
  port: 8082
  gallery:
  - 1.jpg
  - 2.jpg
  - 3.jpg
  path: ''
  defaultPassword: moneyprintergobrrr
  torOnly: false
containers:
- image: pihole/pihole:v5.8.1@sha256:d2f764c4531515a1b93d5a8d1d82272ddc961e580f19c84ed764e4fa863823b1
  ports:
  - '53:53'
  - 53:53/udp
  - ${APP_PI_HOLE_PORT}:80
  environment:
    VIRTUAL_HOST: ${APP_DOMAIN}
    WEBPASSWORD: moneyprintergobrrr
  name: server
  data:
  - data/dnsmasq:/etc/dnsmasq.d/
  - data/pihole:/etc/pihole/
  ip: $APP_PI_HOLE_IP
